///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();
  static const String imagesRectangle2 = 'assets/images/rectangle2.png';
  static const String imagesOurHappy4 = 'assets/images/our_happy4.png';

  static const String imagesRectangle_19 = 'assets/images/Rectangle 19.png';

  static const String imagesVector2 = 'assets/images/vector2.png';
  static const String imagesSecImage = 'assets/images/sec_image.png';
  static const String imagesBedroom = 'assets/images/bedroom.png';
  static const String imagesCalendarImage = 'assets/images/calendar_image.png';
  static const String imagesCertificateOutline = 'assets/images/certificate_outline.png';
  static const String imagesCustomerImage = 'assets/images/customer_image.png';
  static const String imagesExteriorProject = 'assets/images/exterior_project.png';
  static const String imagesFacebookLogo = 'assets/images/facebook_logo.png';
  static const String imagesFirstImage = 'assets/images/first_image.png';
  static const String imagesGreyBeauty = 'assets/images/grey_beauty.png';
  static const String imagesHomeOffice = 'assets/images/home_office.png';
  static const String imagesHomeSmileImage = 'assets/images/home_smile_image.png';
  static const String imagesImage1 = 'assets/images/image1.png';
  static const String imagesImage2 = 'assets/images/image2.png';
  static const String imagesImage3 = 'assets/images/image3.png';
  static const String imagesImage4 = 'assets/images/image4.png';
  static const String imagesInstagramLogo = 'assets/images/instagram_logo.png';
  static const String imagesLandIntiror_design = 'assets/images/land_intiror_design.png';
  static const String imagesLinkedinLogo = 'assets/images/linkedin_logo.png';
  static const String imagesLivingRoom = 'assets/images/living_room.png';
  static const String imagesModernInterior = 'assets/images/modern_interior.png';
  static const String imagesModularKitchen = 'assets/images/modular_kitchen.png';
  static const String imagesOurHappy1 = 'assets/images/our_happy1.png';
  static const String imagesOurHappy2 = 'assets/images/our_happy2.png';
  static const String imagesOurHappy3 = 'assets/images/our_happy3.png';
  static const String imagesPlantationInterior = 'assets/images/plantation_interior.png';
  static const String imagesProduct1 = 'assets/images/product1.png';
  static const String imagesProduct2 = 'assets/images/product2.png';
  static const String imagesProduct3 = 'assets/images/product3.png';
  static const String imagesProduct4 = 'assets/images/product4.png';
  static const String imagesProduct5 = 'assets/images/product5.png';
  static const String imagesProduct6 = 'assets/images/product6.png';
  static const String imagesRectangle1 = 'assets/images/rectangle1.png';
  static const String imagesRoleOfFurnitures = 'assets/images/role_of_furnitures.png';
  static const String imagesTwitterLogo = 'assets/images/twitter_logo.png';
  static const String imagesYoutubeLogo = 'assets/images/youtube_logo.png';

}
